In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('https://raw.githubusercontent.com/frankData612/data_612/master/stock_data/stocks_yahoo.csv')

df.shape

(67905, 19)

In [ ]:
df.dtypes

no                     int64
date                  object
company_name          object
price_at_close        object
price_change          object
price_after_hours     object
previous_close        object
today opened          object
price range           object
52 week range         object
volume                object
average volume        object
market cap            object
beta (3Y Monthly)    float64
PE Ratio              object
EPS                   object
earnings date         object
Dividend Yield        object
1Y target est         object
dtype: object

In [ ]:
df.isnull().sum()

no                       0
date                     0
company_name             0
price_at_close         144
price_change           144
price_after_hours      144
previous_close         144
today opened           155
price range            149
52 week range          248
volume                 153
average volume        1321
market cap             607
beta (3Y Monthly)     4742
PE Ratio              7685
EPS                   2943
earnings date        10294
Dividend Yield         280
1Y target est         9974
dtype: int64

In [ ]:
dg = df['company_name'].str.split("- ", n=1, expand=True)
df['Symbol'] = dg[0]
df['company_name'] = dg[1]
df['company_name'] = df.company_name.astype('category')

dh = df['52 week range'].str.split("- ", n=1, expand=True)
df['52_week_range_lo'] = dh[0]
df['52_week_range_hi'] = dh[1]

di = df['price_change'].str.split("(", n=1, expand=True)
df['price_change_amt'] = di[0]
#df['price_change_amt'] = df.price_change_amt.str.strip("+")
#df['price_change_amt'] = df.price_change_amt.astype('float')
df['price_change_prct'] = di[1]
df['price_change_prct'] = df.price_change_prct.str.strip('%)')
df['price_change_prct'] = df.price_change_prct.astype('float')

dj = df['price range'].str.split("- ", n=1, expand=True)
df['price_range_lo'] = dj[0]
df['price_range_hi'] = dj[1]

df.drop(columns=["no","52 week range", "price_change", "price_change"], inplace=True)
df['date'] = pd.to_datetime(df['date'], format='%b %d %Y')
df

            date  ... price_range_hi
0     2019-11-21  ...       1,312.45
1     2019-11-21  ...       1,311.04
2     2019-11-21  ...         134.17
3     2019-11-21  ...         149.80
4     2019-11-21  ...         264.01
...          ...  ...            ...
67900 2020-04-28  ...           9.31
67901 2020-04-28  ...          30.75
67902 2020-04-28  ...           7.10
67903 2020-04-28  ...          56.21
67904 2020-04-28  ...          71.20

[67905 rows x 23 columns]

In [ ]:
df.dtypes

date                 datetime64[ns]
company_name               category
price_at_close               object
price_after_hours            object
previous_close               object
today opened                 object
price range                  object
volume                       object
average volume               object
market cap                   object
beta (3Y Monthly)           float64
PE Ratio                     object
EPS                          object
earnings date                object
Dividend Yield               object
1Y target est                object
Symbol                       object
52_week_range_lo             object
52_week_range_hi             object
price_change_amt             object
price_change_prct           float64
price_range_lo               object
price_range_hi               object
dtype: object